name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clippy:
    uses: ./.github/workflows/_rust-ci.yml
    with:
      job_name: Run clippy
      step_name: Run clippy
      components: clippy
      command: cargo clippy --workspace --all-targets --all-features -- -D warnings