name: Build binary release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    uses: ./.github/workflows/_rust-ci.yml
    with:
      job_name: Build release
      step_name: Build release
      command: cargo build --release