name: Rustfmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rustfmt:
    uses: ./.github/workflows/_rust-ci.yml
    with:
      job_name: Check formatting
      step_name: Check formatting
      components: rustfmt
      command: cargo fmt --all -- --check