name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_rust-ci.yml
    with:
      job_name: Run tests
      step_name: Run tests
      command: cargo test --workspace --all-targets --all-features --locked